/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_bass_easySerial_SerialPort_open
  (JNIEnv *, jobject, jstring, jint, jint);

JNIEXPORT jobject JNICALL Java_com_bass_easySerial_SerialPort_open2
        (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bass_easySerial_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
